name = "solid-octujjjo-soonjbjbskjsk"
main = "worker.js"
compatibility_date = "2024-04-01"

[vars]
GITHUB_REPO_OWNER = "hiplitewhat"
GITHUB_REPO_NAME = "a"
VERSION_FILE_PATH = "version.txt"
GITHUB_BRANCH = "main"
